### ISSUE TITLE
teleinfo2mqtt arrête d'envoyer des informations au bout de quelques minutes

### ISSUE THREAD

**Issue by vdanjean** [fmartinou/teleinfo2mqtt#93]
Bonjour,

Mon compteur est un linky en mode standard. J'ai acheté un convertisseur pour avoir les infos sur une ligne série. Avec minicom, je vois bien les bonnes infos arriver depuis l'USB en continu.
J'ai mis en place teleinfo2mqtt avec hassio. Quand je le lance, les infos correctes sont bien remontées. Les sensors affichent des info cohérentes. Mais, après quelques minutes (moins de 10 min, plutôt 1 ou 2), plus rien n'évolue (y compris sur plusieurs jours si je ne fais rien).
Ça reste comme cela jusqu'à ce que je relance le module teleinfo2mqtt (depuis l'interface web de HA). Dans ce cas, je récupère les nouvelles valeurs, ça marche quelques minutes, puis les relevés s'arrêtent.
Si je mets les logs en mode DEBUG, je vois bien les trames traitées, mais, au bout de quelques minutes, les messages s'arrêtent brutalement, sans aucun message différent des précédents.

Si je regarde le brocker mqtt, par exemple avec `mosquitto_sub -t '#' -u admin -P XXXX -v`, là encore, je vois bien des messages publiés sur teleinfo/XXXXXXX et teleinfo/status pendant quelques minutes, puis plus rien de teleinfo2mqtt (je continue bien de voir les updates de zigbee2mqtt par contre).

Avez-vous une idée de pouquoi teleinfo2mqtt s'arrête systématiquement de fonctionner au bout de quelques minutes sans laisser de trace dans les logs ? Des idées pour creuser un peu plus et récolter de l'info ?

Cordialement,

**Comment by plop3** [comment]
J'ai trouvé la raison de mon problème: des micro-coupures EDF
Micro-coupure -> Plus de remontée d'infos jusqu'au redémarrage de teleinfo2mqtt

**Comment by Braccac** [comment]
J'ai des panneaux solaires aussi mais comme le linky renvoie des volts ampères la valeur varie même si on est à zéro il y a toujours un équipement qui renvoie une puissance apparente

**Comment by plop3** [comment]
J'ai créé un capteur mqtt TeleinfoStatus et une automatisation.
Si le status passe de "up" à autre chose, le module est redémarré.

**Comment by plop3** [comment]
Je viens d'avoir une micro-coupure.
Mon automatisation a fonctionné et redémarré Teleinfo2mqtt \o/

**Comment by vdanjean** [comment]
J'ai dû m'occuper d'autres choses et débrancher mon module teleinfo quelques mois. Je viens de le remettre et j'ai toujours la même chose. Les infos téléinfo arrivent par un adaptateur série sur USB. Même s'il y a une micro coupure du compteur, les infos doivent continuer d'arriver par la ligne série (éventuellement avec quelques données incorrectes au moment de la micro-coupure). Je pense donc vraiment qu'il faudrait rendre le code plus robuste.
Je ne connais pas du tout l'écosystème javascript/nodejs. Je vais voir si j'arrive à faire quelques chose, sinon je réimplémenterais dans un autre langage (perl ou python probablement).

**Comment by vdanjean** [comment]
@plop3 : peux-tu décrire un peu plus ton setup ? Le binary_sensor, tu le mets dans quel fichier de config ? Et ton automatisation ressemble à quoi pour redémarrer une app ?

**Comment by plop3** [comment]
Mon binary_sensor est dans configuration.yaml:
```
mqtt:
  binary_sensor:
    - name: "TeleinfoStatus"
      state_topic: "teleinfo/status"
      payload_on: "up"
      payload_off: ''
      #expire_after: 30
      off_delay: '120'
```
Mon automatisation:
```
alias: Teleinfo restart
description: ""
triggers:
  - trigger: state
    entity_id:
      - binary_sensor.teleinfostatus
    from:
      - "on"
conditions: []
actions:
  - action: hassio.addon_restart
    metadata: {}
    data:
      addon: 6b64d821_teleinfo2mqtt
    enabled: true
  - delay:
      hours: 0
      minutes: 2
      seconds: 0
      milliseconds: 0
    enabled: true
mode: queued
max: 10
```
